POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Diego",
  "email": "diego@gmail.com",
  "referrer":"069aa48a-5fff-4113-9812-94bcc8286ac2"
}
###


GET http://localhost:3333/invites/069aa48a-5fff-4113-9812-94bcc8286ac2
###

GET http://localhost:3333/subscribers/069aa48a-5fff-4113-9812-94bcc8286ac2/ranking/clicks
###

GET http://localhost:3333/subscribers/069aa48a-5fff-4113-9812-94bcc8286ac2/ranking/count
###

GET http://localhost:3333/subscribers/069aa48a-5fff-4113-9812-94bcc8286ac2/ranking/position
###

GET http://localhost:3333/ranking